apiVersion: v1
kind: Service
metadata:
  name: docusaurus-dom
spec:
  type: NodePort
  selector:
    app: docusaurus-dom
  ports:
    - port: 80            # inside the cluster
      targetPort: 80      # listens on
      nodePort: 31844     # external node port
      protocol: TCP
