apiVersion: apps/v1
kind: Deployment
metadata:
  name: docusaurus-dom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docusaurus-dom
  template:
    metadata:
      labels:
        app: docusaurus-dom
    spec:
      containers:
      - name: docusaurus-dom
        image: cejkadominik/docusaurus-site:latest
        ports:
          - containerPort: 80
